apiVersion: "v1"
kind: Service
metadata:
  labels:
    {{ include "helm-charts.labels" . | nindent 4 }}
  name: {{ .Values.service.name | quote }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}